---
User:
  columns:
    login: string
    password: string
    name: string
    email: string
    language: string
    use_wysiwyg: boolean

Node:
  actAs:
    Timestampable:
    NestedSet:
  columns:
    title: string
    filtered_title: string
    in_navigation: boolean
    navigation: string
    permalink: string
    publish_status: integer
    author_id: integer(8)
    node_type_id: integer(8)
    template_file: string
  relations:
    User:
      local: author_id
      foreign: id
      alias: Author
      foreignAlias: Nodes
    NodeType:
      local: node_type_id
      foreign: id
      foreignAlias: Nodes

Node_Page:
  inheritance:
    extends: Node
    type: column_aggregation
    keyField: class
    keyValue: Contener_Domain_Node_Page

Node_Link:
  inheritance:
    extends: Node
    type: column_aggregation
    keyField: class
    keyValue: Contener_Domain_Node_Link

Slot:
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: node_id
  columns:
    node_id: integer(8)
    class: string
    name: string
    body: clob
  relations:
    Node:
      foreignAlias: Slots
      onDelete: CASCADE

NodeType:
  columns:
    title: string
    body: clob

NodeTemplate:
  columns:
    title: string
    name: string
    type_id: integer(8)
  relations:
    NodeType:
      local: type_id
      foreignAlias: Templates
      onDelete: CASCADE
  