<?php

/**
 * Contener_Domain_Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Contener_Domain_Page extends Contener_Domain_Base_Page
{
    static function fetch($id)
    {
        $page = Doctrine_Query::create()
            ->select()
            ->from('Contener_Domain_Page p, p.Slots s, p.Author a')
            ->where('p.id = ?', $id)
            ->orderBy('s.lft')
            ->fetchOne(array(), 'Contener_Database_Hydrator');
        
        return $page;
    }
    
    static function fetchAll()
    {
        $page = Doctrine_Query::create()
            ->select()
            ->from('Contener_Domain_Page p, p.Slots s, p.Author a')
            ->orderBy('p.lft, s.lft')
            ->execute(array(), 'Contener_Database_Hydrator');
        
        return $page;
    }
}
