<?php

/**
 * Contener_Domain_Base_PageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $class
 * @property clob $body
 * @property Doctrine_Collection $Templates
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Contener_Domain_Base_PageType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('page_type');
        $this->hasColumn('class', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contener_Domain_PageTemplate as Templates', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}