<?php

/**
 * Contener_Domain_Base_NodeTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $type_id
 * @property Contener_Domain_NodeType $NodeType
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Contener_Domain_Base_NodeTemplate extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('node_template');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('type_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contener_Domain_NodeType as NodeType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}