<?php

/**
 * Contener_Domain_Base_Template
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $theme_id
 * @property string $name
 * @property string $file_path
 * @property Contener_Domain_Theme $Theme
 * @property Doctrine_Collection $Slots
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Contener_Domain_Base_Template extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('template');
        $this->hasColumn('theme_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('file_path', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contener_Domain_Theme as Theme', array(
             'local' => 'theme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Contener_Domain_Slot_Template as Slots', array(
             'local' => 'id',
             'foreign' => 'template_id'));
    }
}